"""Create conversation table

Revision ID: 0a65ee47b8a8
Revises: 30b391ca28e5
Create Date: 2024-12-04 15:19:00.872168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a65ee47b8a8"
down_revision: Union[str, None] = "30b391ca28e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(), nullable=False, unique=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_email"),
    )

    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_conversations_user_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("sender", sa.Enum("user", "bot", name="sender_enum"), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.TIMESTAMP(), default=sa.func.current_timestamp()),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], name="fk_message_conversation_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("conversations")
    op.drop_table("messages")
    # ### end Alembic commands ###
